version: '3.8'

services:
  app:
    build: .
    ports:
      - "${SERVER_PORT}:8080"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./src:/app/src  # Monta o código-fonte como volume

  db:
    image: postgres:13
    ports:
      - "5432:5432"  # Alterado para 5434
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: